const SET_TOKEN = 'SETTOKEN';
const CLEAR_TOKEN = 'CLEARTOKEN';
const SET_USERINFO = 'SETUSERINFO';
const CLEAR_USERINFO = 'CLEARUSERINFO';
const SET_ROLES = 'SETROLES';
const CLEAR_ROLES = 'CLEARROLES';
const CLEAR_LOGININFO = 'CLEARLOGININFO';
const UPDATE_USERINFO = 'UPDATEUSERINFO';

const SET_ROUTERS = 'SETROUTERS';

const SET_BREADCRUMB = 'SETBREADCRUMB';

const GET_HOST = 'GETHOST';

const SET_THEME = 'SET_THEME';

export default {
  SET_TOKEN,
  CLEAR_TOKEN,
  SET_USERINFO,
  CLEAR_USERINFO,
  SET_ROLES,
  CLEAR_ROLES,
  CLEAR_LOGININFO,
  SET_ROUTERS,
  SET_BREADCRUMB,
  UPDATE_USERINFO,
  GET_HOST,
  SET_THEME
};
